AllCops:
  TargetRubyVersion: 2.3

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 36
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
