Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

AllCops:
  Exclude:
    - spec/**/*
